version: '3'
services:
  python3:
    restart: always
    build: .
    container_name: 'python3_env'
    tty: true
    working_dir: '/src'
    volumes:
      - ./src:/src
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all